// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: historysql.proto

package io.grpc.history;

public final class HistoryRecord {
  private HistoryRecord() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_historyrecord_RequestOperateSql_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_historyrecord_RequestOperateSql_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_historyrecord_ResponseOperateSql_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_historyrecord_ResponseOperateSql_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020historysql.proto\022\rhistoryrecord\"!\n\021Req" +
      "uestOperateSql\022\014\n\004name\030\001 \001(\t\"%\n\022Response" +
      "OperateSql\022\017\n\007message\030\001 \001(\t2^\n\007Greeter\022S" +
      "\n\nsendOptSql\022 .historyrecord.RequestOper" +
      "ateSql\032!.historyrecord.ResponseOperateSq" +
      "l\"\000B(\n\017io.grpc.historyB\rHistoryRecordP\001\242" +
      "\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_historyrecord_RequestOperateSql_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_historyrecord_RequestOperateSql_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_historyrecord_RequestOperateSql_descriptor,
        new String[] { "Name", });
    internal_static_historyrecord_ResponseOperateSql_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_historyrecord_ResponseOperateSql_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_historyrecord_ResponseOperateSql_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
