// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: historysql.proto

package io.grpc.history;

public interface RequestOperateSqlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:historyrecord.RequestOperateSql)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
