// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: historysql.proto

package io.grpc.history;

public interface ResponseOperateSqlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:historyrecord.ResponseOperateSql)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
